_wandb:
    value:
        cli_version: 0.21.3
        e:
            79zkn86p6mc6xnr6u9tjcqmaxin17kgb:
                codePath: redesneuronales_pytorch.py
                codePathLocal: redesneuronales_pytorch.py
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "478962855936"
                        used: "397081563136"
                email: a01637721@tec.mx
                executable: C:\Users\USUARIO\AppData\Local\Programs\Python\Python312\python.exe
                host: DESKTOP-QDJU2PR
                memory:
                    total: "8470659072"
                os: Windows-10-10.0.19045-SP0
                program: C:\Users\USUARIO\Desktop\SemestreVII\Aprendizaje\redesneuronales_pytorch.py
                python: CPython 3.12.4
                root: C:\Users\USUARIO\Desktop\SemestreVII\Aprendizaje
                startedAt: "2025-09-06T00:10:33.232633Z"
                writerId: 79zkn86p6mc6xnr6u9tjcqmaxin17kgb
        m: []
        python_version: 3.12.4
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 2
                - 13
            "4": 3.12.4
            "5": 0.21.3
            "8":
                - 3
            "10":
                - 20
            "12": 0.21.3
            "13": windows-amd64
