_wandb:
    value:
        cli_version: 0.21.3
        e:
            q7ooepgcgfkgae180dl8k9uwcv46z03c:
                codePath: clasificador_multiclase_pytorch_MNIST.py
                codePathLocal: clasificador_multiclase_pytorch_MNIST.py
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "478962855936"
                        used: "397046546432"
                email: a01637721@tec.mx
                executable: C:\Users\USUARIO\AppData\Local\Programs\Python\Python312\python.exe
                host: DESKTOP-QDJU2PR
                memory:
                    total: "8470659072"
                os: Windows-10-10.0.19045-SP0
                program: C:\Users\USUARIO\Desktop\SemestreVII\Aprendizaje\clasificador_multiclase_pytorch_MNIST.py
                python: CPython 3.12.4
                root: C:\Users\USUARIO\Desktop\SemestreVII\Aprendizaje
                startedAt: "2025-09-06T00:30:09.094357Z"
                writerId: q7ooepgcgfkgae180dl8k9uwcv46z03c
        m: []
        python_version: 3.12.4
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 2
                - 13
                - 16
            "4": 3.12.4
            "5": 0.21.3
            "8":
                - 3
            "12": 0.21.3
            "13": windows-amd64
batch_size:
    value: 64
dropout:
    value: 0
epochs:
    value: 10
lr:
    value: 0.001
weight_decay:
    value: 0
